//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 02.03.2017 15:12:32
namespace CarWashManager
{
    
    /// <summary>
    /// There are no comments for CWMEntities in the schema.
    /// </summary>
    public partial class CWMEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new CWMEntities object using the connection string found in the 'CWMEntities' section of the application configuration file.
        /// </summary>
        public CWMEntities() : 
                base("name=CWMEntities", "CWMEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new CWMEntities object.
        /// </summary>
        public CWMEntities(string connectionString) : 
                base(connectionString, "CWMEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new CWMEntities object.
        /// </summary>
        public CWMEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "CWMEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for CAR in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<CAR> CAR
        {
            get
            {
                if ((this._CAR == null))
                {
                    this._CAR = base.CreateQuery<CAR>("[CAR]");
                }
                return this._CAR;
            }
        }
        private global::System.Data.Objects.ObjectQuery<CAR> _CAR;
        /// <summary>
        /// There are no comments for CARCLASS in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<CARCLASS> CARCLASS
        {
            get
            {
                if ((this._CARCLASS == null))
                {
                    this._CARCLASS = base.CreateQuery<CARCLASS>("[CARCLASS]");
                }
                return this._CARCLASS;
            }
        }
        private global::System.Data.Objects.ObjectQuery<CARCLASS> _CARCLASS;
        /// <summary>
        /// There are no comments for EMPLOYEE in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<EMPLOYEE> EMPLOYEE
        {
            get
            {
                if ((this._EMPLOYEE == null))
                {
                    this._EMPLOYEE = base.CreateQuery<EMPLOYEE>("[EMPLOYEE]");
                }
                return this._EMPLOYEE;
            }
        }
        private global::System.Data.Objects.ObjectQuery<EMPLOYEE> _EMPLOYEE;
        /// <summary>
        /// There are no comments for JOB in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<JOB> JOB
        {
            get
            {
                if ((this._JOB == null))
                {
                    this._JOB = base.CreateQuery<JOB>("[JOB]");
                }
                return this._JOB;
            }
        }
        private global::System.Data.Objects.ObjectQuery<JOB> _JOB;
        /// <summary>
        /// There are no comments for LINE in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<LINE> LINE
        {
            get
            {
                if ((this._LINE == null))
                {
                    this._LINE = base.CreateQuery<LINE>("[LINE]");
                }
                return this._LINE;
            }
        }
        private global::System.Data.Objects.ObjectQuery<LINE> _LINE;
        /// <summary>
        /// There are no comments for PACKAGE in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<PACKAGE> PACKAGE
        {
            get
            {
                if ((this._PACKAGE == null))
                {
                    this._PACKAGE = base.CreateQuery<PACKAGE>("[PACKAGE]");
                }
                return this._PACKAGE;
            }
        }
        private global::System.Data.Objects.ObjectQuery<PACKAGE> _PACKAGE;
        /// <summary>
        /// There are no comments for PRICELIST in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<PRICELIST> PRICELIST
        {
            get
            {
                if ((this._PRICELIST == null))
                {
                    this._PRICELIST = base.CreateQuery<PRICELIST>("[PRICELIST]");
                }
                return this._PRICELIST;
            }
        }
        private global::System.Data.Objects.ObjectQuery<PRICELIST> _PRICELIST;
        /// <summary>
        /// There are no comments for JOBVIEW in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<JOBVIEW> JOBVIEW
        {
            get
            {
                if ((this._JOBVIEW == null))
                {
                    this._JOBVIEW = base.CreateQuery<JOBVIEW>("[JOBVIEW]");
                }
                return this._JOBVIEW;
            }
        }
        private global::System.Data.Objects.ObjectQuery<JOBVIEW> _JOBVIEW;
        /// <summary>
        /// There are no comments for REMOVEDJOB in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<REMOVEDJOB> REMOVEDJOB
        {
            get
            {
                if ((this._REMOVEDJOB == null))
                {
                    this._REMOVEDJOB = base.CreateQuery<REMOVEDJOB>("[REMOVEDJOB]");
                }
                return this._REMOVEDJOB;
            }
        }
        private global::System.Data.Objects.ObjectQuery<REMOVEDJOB> _REMOVEDJOB;
        /// <summary>
        /// There are no comments for CAR in the schema.
        /// </summary>
        public void AddToCAR(CAR cAR)
        {
            base.AddObject("CAR", cAR);
        }
        /// <summary>
        /// There are no comments for CARCLASS in the schema.
        /// </summary>
        public void AddToCARCLASS(CARCLASS cARCLASS)
        {
            base.AddObject("CARCLASS", cARCLASS);
        }
        /// <summary>
        /// There are no comments for EMPLOYEE in the schema.
        /// </summary>
        public void AddToEMPLOYEE(EMPLOYEE eMPLOYEE)
        {
            base.AddObject("EMPLOYEE", eMPLOYEE);
        }
        /// <summary>
        /// There are no comments for JOB in the schema.
        /// </summary>
        public void AddToJOB(JOB jOB)
        {
            base.AddObject("JOB", jOB);
        }
        /// <summary>
        /// There are no comments for LINE in the schema.
        /// </summary>
        public void AddToLINE(LINE lINE)
        {
            base.AddObject("LINE", lINE);
        }
        /// <summary>
        /// There are no comments for PACKAGE in the schema.
        /// </summary>
        public void AddToPACKAGE(PACKAGE pACKAGE)
        {
            base.AddObject("PACKAGE", pACKAGE);
        }
        /// <summary>
        /// There are no comments for PRICELIST in the schema.
        /// </summary>
        public void AddToPRICELIST(PRICELIST pRICELIST)
        {
            base.AddObject("PRICELIST", pRICELIST);
        }
        /// <summary>
        /// There are no comments for JOBVIEW in the schema.
        /// </summary>
        public void AddToJOBVIEW(JOBVIEW jOBVIEW)
        {
            base.AddObject("JOBVIEW", jOBVIEW);
        }
        /// <summary>
        /// There are no comments for REMOVEDJOB in the schema.
        /// </summary>
        public void AddToREMOVEDJOB(REMOVEDJOB rEMOVEDJOB)
        {
            base.AddObject("REMOVEDJOB", rEMOVEDJOB);
        }
    }
    /// <summary>
    /// There are no comments for CWMModel.CAR in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CWMModel", Name="CAR")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class CAR : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new CAR object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="cNAME">Initial value of CNAME.</param>
        /// <param name="iDCLASS">Initial value of IDCLASS.</param>
        public static CAR CreateCAR(int id, string cNAME, int iDCLASS)
        {
            CAR cAR = new CAR();
            cAR.ID = id;
            cAR.CNAME = cNAME;
            cAR.IDCLASS = iDCLASS;
            return cAR;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property CNAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CNAME
        {
            get
            {
                return this._CNAME;
            }
            set
            {
                this.OnCNAMEChanging(value);
                this.ReportPropertyChanging("CNAME");
                this._CNAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CNAME");
                this.OnCNAMEChanged();
            }
        }
        private string _CNAME;
        partial void OnCNAMEChanging(string value);
        partial void OnCNAMEChanged();
        /// <summary>
        /// There are no comments for Property IDCLASS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IDCLASS
        {
            get
            {
                return this._IDCLASS;
            }
            set
            {
                this.OnIDCLASSChanging(value);
                this.ReportPropertyChanging("IDCLASS");
                this._IDCLASS = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IDCLASS");
                this.OnIDCLASSChanged();
            }
        }
        private int _IDCLASS;
        partial void OnIDCLASSChanging(int value);
        partial void OnIDCLASSChanged();
    }
    /// <summary>
    /// There are no comments for CWMModel.CARCLASS in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CWMModel", Name="CARCLASS")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class CARCLASS : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new CARCLASS object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="cNAME">Initial value of CNAME.</param>
        /// <param name="aNNOTATION">Initial value of ANNOTATION.</param>
        public static CARCLASS CreateCARCLASS(int id, string cNAME, string aNNOTATION)
        {
            CARCLASS cARCLASS = new CARCLASS();
            cARCLASS.ID = id;
            cARCLASS.CNAME = cNAME;
            cARCLASS.ANNOTATION = aNNOTATION;
            return cARCLASS;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property CNAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CNAME
        {
            get
            {
                return this._CNAME;
            }
            set
            {
                this.OnCNAMEChanging(value);
                this.ReportPropertyChanging("CNAME");
                this._CNAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CNAME");
                this.OnCNAMEChanged();
            }
        }
        private string _CNAME;
        partial void OnCNAMEChanging(string value);
        partial void OnCNAMEChanged();
        /// <summary>
        /// There are no comments for Property ANNOTATION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ANNOTATION
        {
            get
            {
                return this._ANNOTATION;
            }
            set
            {
                this.OnANNOTATIONChanging(value);
                this.ReportPropertyChanging("ANNOTATION");
                this._ANNOTATION = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ANNOTATION");
                this.OnANNOTATIONChanged();
            }
        }
        private string _ANNOTATION;
        partial void OnANNOTATIONChanging(string value);
        partial void OnANNOTATIONChanged();
    }
    /// <summary>
    /// There are no comments for CWMModel.EMPLOYEE in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CWMModel", Name="EMPLOYEE")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class EMPLOYEE : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new EMPLOYEE object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        public static EMPLOYEE CreateEMPLOYEE(int id)
        {
            EMPLOYEE eMPLOYEE = new EMPLOYEE();
            eMPLOYEE.ID = id;
            return eMPLOYEE;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property ENAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ENAME
        {
            get
            {
                return this._ENAME;
            }
            set
            {
                this.OnENAMEChanging(value);
                this.ReportPropertyChanging("ENAME");
                this._ENAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ENAME");
                this.OnENAMEChanged();
            }
        }
        private string _ENAME;
        partial void OnENAMEChanging(string value);
        partial void OnENAMEChanged();
        /// <summary>
        /// There are no comments for Property DELETED in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> DELETED
        {
            get
            {
                return this._DELETED;
            }
            set
            {
                this.OnDELETEDChanging(value);
                this.ReportPropertyChanging("DELETED");
                this._DELETED = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DELETED");
                this.OnDELETEDChanged();
            }
        }
        private global::System.Nullable<bool> _DELETED;
        partial void OnDELETEDChanging(global::System.Nullable<bool> value);
        partial void OnDELETEDChanged();
    }
    /// <summary>
    /// There are no comments for CWMModel.JOB in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CWMModel", Name="JOB")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class JOB : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new JOB object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="iDEMP">Initial value of IDEMP.</param>
        /// <param name="iDPACKAGE">Initial value of IDPACKAGE.</param>
        /// <param name="jOBDATE">Initial value of JOBDATE.</param>
        /// <param name="tOTALCOST">Initial value of TOTALCOST.</param>
        /// <param name="lINE">Initial value of LINE.</param>
        /// <param name="iDCLASS">Initial value of IDCLASS.</param>
        /// <param name="nPLATE">Initial value of NPLATE.</param>
        /// <param name="iDCAR">Initial value of IDCAR.</param>
        public static JOB CreateJOB(int id, int iDEMP, int iDPACKAGE, global::System.DateTime jOBDATE, int tOTALCOST, int lINE, int iDCLASS, string nPLATE, int iDCAR)
        {
            JOB jOB = new JOB();
            jOB.ID = id;
            jOB.IDEMP = iDEMP;
            jOB.IDPACKAGE = iDPACKAGE;
            jOB.JOBDATE = jOBDATE;
            jOB.TOTALCOST = tOTALCOST;
            jOB.LINE = lINE;
            jOB.IDCLASS = iDCLASS;
            jOB.NPLATE = nPLATE;
            jOB.IDCAR = iDCAR;
            return jOB;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property IDEMP in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IDEMP
        {
            get
            {
                return this._IDEMP;
            }
            set
            {
                this.OnIDEMPChanging(value);
                this.ReportPropertyChanging("IDEMP");
                this._IDEMP = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IDEMP");
                this.OnIDEMPChanged();
            }
        }
        private int _IDEMP;
        partial void OnIDEMPChanging(int value);
        partial void OnIDEMPChanged();
        /// <summary>
        /// There are no comments for Property IDPACKAGE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IDPACKAGE
        {
            get
            {
                return this._IDPACKAGE;
            }
            set
            {
                this.OnIDPACKAGEChanging(value);
                this.ReportPropertyChanging("IDPACKAGE");
                this._IDPACKAGE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IDPACKAGE");
                this.OnIDPACKAGEChanged();
            }
        }
        private int _IDPACKAGE;
        partial void OnIDPACKAGEChanging(int value);
        partial void OnIDPACKAGEChanged();
        /// <summary>
        /// There are no comments for Property JOBDATE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime JOBDATE
        {
            get
            {
                return this._JOBDATE;
            }
            set
            {
                this.OnJOBDATEChanging(value);
                this.ReportPropertyChanging("JOBDATE");
                this._JOBDATE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("JOBDATE");
                this.OnJOBDATEChanged();
            }
        }
        private global::System.DateTime _JOBDATE;
        partial void OnJOBDATEChanging(global::System.DateTime value);
        partial void OnJOBDATEChanged();
        /// <summary>
        /// There are no comments for Property TOTALCOST in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int TOTALCOST
        {
            get
            {
                return this._TOTALCOST;
            }
            set
            {
                this.OnTOTALCOSTChanging(value);
                this.ReportPropertyChanging("TOTALCOST");
                this._TOTALCOST = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TOTALCOST");
                this.OnTOTALCOSTChanged();
            }
        }
        private int _TOTALCOST;
        partial void OnTOTALCOSTChanging(int value);
        partial void OnTOTALCOSTChanged();
        /// <summary>
        /// There are no comments for Property LINE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int LINE
        {
            get
            {
                return this._LINE;
            }
            set
            {
                this.OnLINEChanging(value);
                this.ReportPropertyChanging("LINE");
                this._LINE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LINE");
                this.OnLINEChanged();
            }
        }
        private int _LINE;
        partial void OnLINEChanging(int value);
        partial void OnLINEChanged();
        /// <summary>
        /// There are no comments for Property IDCLASS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IDCLASS
        {
            get
            {
                return this._IDCLASS;
            }
            set
            {
                this.OnIDCLASSChanging(value);
                this.ReportPropertyChanging("IDCLASS");
                this._IDCLASS = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IDCLASS");
                this.OnIDCLASSChanged();
            }
        }
        private int _IDCLASS;
        partial void OnIDCLASSChanging(int value);
        partial void OnIDCLASSChanged();
        /// <summary>
        /// There are no comments for Property NPLATE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string NPLATE
        {
            get
            {
                return this._NPLATE;
            }
            set
            {
                this.OnNPLATEChanging(value);
                this.ReportPropertyChanging("NPLATE");
                this._NPLATE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("NPLATE");
                this.OnNPLATEChanged();
            }
        }
        private string _NPLATE;
        partial void OnNPLATEChanging(string value);
        partial void OnNPLATEChanged();
        /// <summary>
        /// There are no comments for Property IDCAR in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IDCAR
        {
            get
            {
                return this._IDCAR;
            }
            set
            {
                this.OnIDCARChanging(value);
                this.ReportPropertyChanging("IDCAR");
                this._IDCAR = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IDCAR");
                this.OnIDCARChanged();
            }
        }
        private int _IDCAR;
        partial void OnIDCARChanging(int value);
        partial void OnIDCARChanged();
    }
    /// <summary>
    /// There are no comments for CWMModel.LINE in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CWMModel", Name="LINE")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class LINE : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new LINE object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        public static LINE CreateLINE(int id)
        {
            LINE lINE = new LINE();
            lINE.ID = id;
            return lINE;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property LNAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LNAME
        {
            get
            {
                return this._LNAME;
            }
            set
            {
                this.OnLNAMEChanging(value);
                this.ReportPropertyChanging("LNAME");
                this._LNAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("LNAME");
                this.OnLNAMEChanged();
            }
        }
        private string _LNAME;
        partial void OnLNAMEChanging(string value);
        partial void OnLNAMEChanged();
    }
    /// <summary>
    /// There are no comments for CWMModel.PACKAGE in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CWMModel", Name="PACKAGE")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class PACKAGE : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new PACKAGE object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="iDJOB">Initial value of IDJOB.</param>
        /// <param name="iDPRICE">Initial value of IDPRICE.</param>
        /// <param name="cOST">Initial value of COST.</param>
        public static PACKAGE CreatePACKAGE(int id, int iDJOB, int iDPRICE, int cOST)
        {
            PACKAGE pACKAGE = new PACKAGE();
            pACKAGE.ID = id;
            pACKAGE.IDJOB = iDJOB;
            pACKAGE.IDPRICE = iDPRICE;
            pACKAGE.COST = cOST;
            return pACKAGE;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property IDJOB in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IDJOB
        {
            get
            {
                return this._IDJOB;
            }
            set
            {
                this.OnIDJOBChanging(value);
                this.ReportPropertyChanging("IDJOB");
                this._IDJOB = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IDJOB");
                this.OnIDJOBChanged();
            }
        }
        private int _IDJOB;
        partial void OnIDJOBChanging(int value);
        partial void OnIDJOBChanged();
        /// <summary>
        /// There are no comments for Property IDPRICE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IDPRICE
        {
            get
            {
                return this._IDPRICE;
            }
            set
            {
                this.OnIDPRICEChanging(value);
                this.ReportPropertyChanging("IDPRICE");
                this._IDPRICE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IDPRICE");
                this.OnIDPRICEChanged();
            }
        }
        private int _IDPRICE;
        partial void OnIDPRICEChanging(int value);
        partial void OnIDPRICEChanged();
        /// <summary>
        /// There are no comments for Property COST in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int COST
        {
            get
            {
                return this._COST;
            }
            set
            {
                this.OnCOSTChanging(value);
                this.ReportPropertyChanging("COST");
                this._COST = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("COST");
                this.OnCOSTChanged();
            }
        }
        private int _COST;
        partial void OnCOSTChanging(int value);
        partial void OnCOSTChanged();
        /// <summary>
        /// There are no comments for Property DELETED in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> DELETED
        {
            get
            {
                return this._DELETED;
            }
            set
            {
                this.OnDELETEDChanging(value);
                this.ReportPropertyChanging("DELETED");
                this._DELETED = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DELETED");
                this.OnDELETEDChanged();
            }
        }
        private global::System.Nullable<bool> _DELETED;
        partial void OnDELETEDChanging(global::System.Nullable<bool> value);
        partial void OnDELETEDChanged();
    }
    /// <summary>
    /// There are no comments for CWMModel.PRICELIST in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CWMModel", Name="PRICELIST")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class PRICELIST : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new PRICELIST object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="pNAME">Initial value of PNAME.</param>
        /// <param name="cOST">Initial value of COST.</param>
        /// <param name="iDCLASS">Initial value of IDCLASS.</param>
        public static PRICELIST CreatePRICELIST(int id, string pNAME, int cOST, int iDCLASS)
        {
            PRICELIST pRICELIST = new PRICELIST();
            pRICELIST.ID = id;
            pRICELIST.PNAME = pNAME;
            pRICELIST.COST = cOST;
            pRICELIST.IDCLASS = iDCLASS;
            return pRICELIST;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property PNAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PNAME
        {
            get
            {
                return this._PNAME;
            }
            set
            {
                this.OnPNAMEChanging(value);
                this.ReportPropertyChanging("PNAME");
                this._PNAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("PNAME");
                this.OnPNAMEChanged();
            }
        }
        private string _PNAME;
        partial void OnPNAMEChanging(string value);
        partial void OnPNAMEChanged();
        /// <summary>
        /// There are no comments for Property COST in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int COST
        {
            get
            {
                return this._COST;
            }
            set
            {
                this.OnCOSTChanging(value);
                this.ReportPropertyChanging("COST");
                this._COST = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("COST");
                this.OnCOSTChanged();
            }
        }
        private int _COST;
        partial void OnCOSTChanging(int value);
        partial void OnCOSTChanged();
        /// <summary>
        /// There are no comments for Property IDCLASS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IDCLASS
        {
            get
            {
                return this._IDCLASS;
            }
            set
            {
                this.OnIDCLASSChanging(value);
                this.ReportPropertyChanging("IDCLASS");
                this._IDCLASS = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IDCLASS");
                this.OnIDCLASSChanged();
            }
        }
        private int _IDCLASS;
        partial void OnIDCLASSChanging(int value);
        partial void OnIDCLASSChanged();
    }
    /// <summary>
    /// There are no comments for CWMModel.JOBVIEW in the schema.
    /// </summary>
    /// <KeyProperties>
    /// EMP
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CWMModel", Name="JOBVIEW")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class JOBVIEW : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new JOBVIEW object.
        /// </summary>
        /// <param name="eMP">Initial value of EMP.</param>
        public static JOBVIEW CreateJOBVIEW(string eMP)
        {
            JOBVIEW jOBVIEW = new JOBVIEW();
            jOBVIEW.EMP = eMP;
            return jOBVIEW;
        }
        /// <summary>
        /// There are no comments for Property EMP in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string EMP
        {
            get
            {
                return this._EMP;
            }
            set
            {
                this.OnEMPChanging(value);
                this.ReportPropertyChanging("EMP");
                this._EMP = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("EMP");
                this.OnEMPChanged();
            }
        }
        private string _EMP;
        partial void OnEMPChanging(string value);
        partial void OnEMPChanged();
        /// <summary>
        /// There are no comments for Property PLATE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PLATE
        {
            get
            {
                return this._PLATE;
            }
            set
            {
                this.OnPLATEChanging(value);
                this.ReportPropertyChanging("PLATE");
                this._PLATE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PLATE");
                this.OnPLATEChanged();
            }
        }
        private string _PLATE;
        partial void OnPLATEChanging(string value);
        partial void OnPLATEChanged();
        /// <summary>
        /// There are no comments for Property T in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string T
        {
            get
            {
                return this._T;
            }
            set
            {
                this.OnTChanging(value);
                this.ReportPropertyChanging("T");
                this._T = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("T");
                this.OnTChanged();
            }
        }
        private string _T;
        partial void OnTChanging(string value);
        partial void OnTChanged();
        /// <summary>
        /// There are no comments for Property PS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PS
        {
            get
            {
                return this._PS;
            }
            set
            {
                this.OnPSChanging(value);
                this.ReportPropertyChanging("PS");
                this._PS = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PS");
                this.OnPSChanged();
            }
        }
        private string _PS;
        partial void OnPSChanging(string value);
        partial void OnPSChanged();
        /// <summary>
        /// There are no comments for Property CAR in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CAR
        {
            get
            {
                return this._CAR;
            }
            set
            {
                this.OnCARChanging(value);
                this.ReportPropertyChanging("CAR");
                this._CAR = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CAR");
                this.OnCARChanged();
            }
        }
        private string _CAR;
        partial void OnCARChanging(string value);
        partial void OnCARChanged();
        /// <summary>
        /// There are no comments for Property COST in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> COST
        {
            get
            {
                return this._COST;
            }
            set
            {
                this.OnCOSTChanging(value);
                this.ReportPropertyChanging("COST");
                this._COST = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("COST");
                this.OnCOSTChanged();
            }
        }
        private global::System.Nullable<int> _COST;
        partial void OnCOSTChanging(global::System.Nullable<int> value);
        partial void OnCOSTChanged();
        /// <summary>
        /// There are no comments for Property EMP2 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string EMP2
        {
            get
            {
                return this._EMP2;
            }
            set
            {
                this.OnEMP2Changing(value);
                this.ReportPropertyChanging("EMP2");
                this._EMP2 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("EMP2");
                this.OnEMP2Changed();
            }
        }
        private string _EMP2;
        partial void OnEMP2Changing(string value);
        partial void OnEMP2Changed();
        /// <summary>
        /// There are no comments for Property PLATE2 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PLATE2
        {
            get
            {
                return this._PLATE2;
            }
            set
            {
                this.OnPLATE2Changing(value);
                this.ReportPropertyChanging("PLATE2");
                this._PLATE2 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PLATE2");
                this.OnPLATE2Changed();
            }
        }
        private string _PLATE2;
        partial void OnPLATE2Changing(string value);
        partial void OnPLATE2Changed();
        /// <summary>
        /// There are no comments for Property T2 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string T2
        {
            get
            {
                return this._T2;
            }
            set
            {
                this.OnT2Changing(value);
                this.ReportPropertyChanging("T2");
                this._T2 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("T2");
                this.OnT2Changed();
            }
        }
        private string _T2;
        partial void OnT2Changing(string value);
        partial void OnT2Changed();
        /// <summary>
        /// There are no comments for Property PS2 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PS2
        {
            get
            {
                return this._PS2;
            }
            set
            {
                this.OnPS2Changing(value);
                this.ReportPropertyChanging("PS2");
                this._PS2 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("PS2");
                this.OnPS2Changed();
            }
        }
        private string _PS2;
        partial void OnPS2Changing(string value);
        partial void OnPS2Changed();
        /// <summary>
        /// There are no comments for Property CAR2 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CAR2
        {
            get
            {
                return this._CAR2;
            }
            set
            {
                this.OnCAR2Changing(value);
                this.ReportPropertyChanging("CAR2");
                this._CAR2 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("CAR2");
                this.OnCAR2Changed();
            }
        }
        private string _CAR2;
        partial void OnCAR2Changing(string value);
        partial void OnCAR2Changed();
        /// <summary>
        /// There are no comments for Property COST2 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> COST2
        {
            get
            {
                return this._COST2;
            }
            set
            {
                this.OnCOST2Changing(value);
                this.ReportPropertyChanging("COST2");
                this._COST2 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("COST2");
                this.OnCOST2Changed();
            }
        }
        private global::System.Nullable<int> _COST2;
        partial void OnCOST2Changing(global::System.Nullable<int> value);
        partial void OnCOST2Changed();
    }
    /// <summary>
    /// There are no comments for CWMModel.REMOVEDJOB in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="CWMModel", Name="REMOVEDJOB")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class REMOVEDJOB : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new REMOVEDJOB object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="iDEMP">Initial value of IDEMP.</param>
        /// <param name="iDPACKAGE">Initial value of IDPACKAGE.</param>
        /// <param name="jOBDATE">Initial value of JOBDATE.</param>
        /// <param name="tOTALCOST">Initial value of TOTALCOST.</param>
        /// <param name="lINE">Initial value of LINE.</param>
        /// <param name="iDCLASS">Initial value of IDCLASS.</param>
        /// <param name="nPLATE">Initial value of NPLATE.</param>
        /// <param name="iDCAR">Initial value of IDCAR.</param>
        /// <param name="iDORIGINALJOB">Initial value of IDORIGINALJOB.</param>
        /// <param name="dATEDELETED">Initial value of DATEDELETED.</param>
        public static REMOVEDJOB CreateREMOVEDJOB(int id, int iDEMP, int iDPACKAGE, global::System.DateTime jOBDATE, int tOTALCOST, int lINE, int iDCLASS, string nPLATE, int iDCAR, int iDORIGINALJOB, global::System.DateTime dATEDELETED)
        {
            REMOVEDJOB rEMOVEDJOB = new REMOVEDJOB();
            rEMOVEDJOB.ID = id;
            rEMOVEDJOB.IDEMP = iDEMP;
            rEMOVEDJOB.IDPACKAGE = iDPACKAGE;
            rEMOVEDJOB.JOBDATE = jOBDATE;
            rEMOVEDJOB.TOTALCOST = tOTALCOST;
            rEMOVEDJOB.LINE = lINE;
            rEMOVEDJOB.IDCLASS = iDCLASS;
            rEMOVEDJOB.NPLATE = nPLATE;
            rEMOVEDJOB.IDCAR = iDCAR;
            rEMOVEDJOB.IDORIGINALJOB = iDORIGINALJOB;
            rEMOVEDJOB.DATEDELETED = dATEDELETED;
            return rEMOVEDJOB;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property IDEMP in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IDEMP
        {
            get
            {
                return this._IDEMP;
            }
            set
            {
                this.OnIDEMPChanging(value);
                this.ReportPropertyChanging("IDEMP");
                this._IDEMP = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IDEMP");
                this.OnIDEMPChanged();
            }
        }
        private int _IDEMP;
        partial void OnIDEMPChanging(int value);
        partial void OnIDEMPChanged();
        /// <summary>
        /// There are no comments for Property IDPACKAGE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IDPACKAGE
        {
            get
            {
                return this._IDPACKAGE;
            }
            set
            {
                this.OnIDPACKAGEChanging(value);
                this.ReportPropertyChanging("IDPACKAGE");
                this._IDPACKAGE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IDPACKAGE");
                this.OnIDPACKAGEChanged();
            }
        }
        private int _IDPACKAGE;
        partial void OnIDPACKAGEChanging(int value);
        partial void OnIDPACKAGEChanged();
        /// <summary>
        /// There are no comments for Property JOBDATE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime JOBDATE
        {
            get
            {
                return this._JOBDATE;
            }
            set
            {
                this.OnJOBDATEChanging(value);
                this.ReportPropertyChanging("JOBDATE");
                this._JOBDATE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("JOBDATE");
                this.OnJOBDATEChanged();
            }
        }
        private global::System.DateTime _JOBDATE;
        partial void OnJOBDATEChanging(global::System.DateTime value);
        partial void OnJOBDATEChanged();
        /// <summary>
        /// There are no comments for Property TOTALCOST in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int TOTALCOST
        {
            get
            {
                return this._TOTALCOST;
            }
            set
            {
                this.OnTOTALCOSTChanging(value);
                this.ReportPropertyChanging("TOTALCOST");
                this._TOTALCOST = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TOTALCOST");
                this.OnTOTALCOSTChanged();
            }
        }
        private int _TOTALCOST;
        partial void OnTOTALCOSTChanging(int value);
        partial void OnTOTALCOSTChanged();
        /// <summary>
        /// There are no comments for Property LINE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int LINE
        {
            get
            {
                return this._LINE;
            }
            set
            {
                this.OnLINEChanging(value);
                this.ReportPropertyChanging("LINE");
                this._LINE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LINE");
                this.OnLINEChanged();
            }
        }
        private int _LINE;
        partial void OnLINEChanging(int value);
        partial void OnLINEChanged();
        /// <summary>
        /// There are no comments for Property IDCLASS in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IDCLASS
        {
            get
            {
                return this._IDCLASS;
            }
            set
            {
                this.OnIDCLASSChanging(value);
                this.ReportPropertyChanging("IDCLASS");
                this._IDCLASS = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IDCLASS");
                this.OnIDCLASSChanged();
            }
        }
        private int _IDCLASS;
        partial void OnIDCLASSChanging(int value);
        partial void OnIDCLASSChanged();
        /// <summary>
        /// There are no comments for Property NPLATE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string NPLATE
        {
            get
            {
                return this._NPLATE;
            }
            set
            {
                this.OnNPLATEChanging(value);
                this.ReportPropertyChanging("NPLATE");
                this._NPLATE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("NPLATE");
                this.OnNPLATEChanged();
            }
        }
        private string _NPLATE;
        partial void OnNPLATEChanging(string value);
        partial void OnNPLATEChanged();
        /// <summary>
        /// There are no comments for Property IDCAR in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IDCAR
        {
            get
            {
                return this._IDCAR;
            }
            set
            {
                this.OnIDCARChanging(value);
                this.ReportPropertyChanging("IDCAR");
                this._IDCAR = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IDCAR");
                this.OnIDCARChanged();
            }
        }
        private int _IDCAR;
        partial void OnIDCARChanging(int value);
        partial void OnIDCARChanged();
        /// <summary>
        /// There are no comments for Property IDORIGINALJOB in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int IDORIGINALJOB
        {
            get
            {
                return this._IDORIGINALJOB;
            }
            set
            {
                this.OnIDORIGINALJOBChanging(value);
                this.ReportPropertyChanging("IDORIGINALJOB");
                this._IDORIGINALJOB = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IDORIGINALJOB");
                this.OnIDORIGINALJOBChanged();
            }
        }
        private int _IDORIGINALJOB;
        partial void OnIDORIGINALJOBChanging(int value);
        partial void OnIDORIGINALJOBChanged();
        /// <summary>
        /// There are no comments for Property DATEDELETED in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime DATEDELETED
        {
            get
            {
                return this._DATEDELETED;
            }
            set
            {
                this.OnDATEDELETEDChanging(value);
                this.ReportPropertyChanging("DATEDELETED");
                this._DATEDELETED = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DATEDELETED");
                this.OnDATEDELETEDChanged();
            }
        }
        private global::System.DateTime _DATEDELETED;
        partial void OnDATEDELETEDChanging(global::System.DateTime value);
        partial void OnDATEDELETEDChanged();
    }
}
