USE [CWM]
GO

/****** Object:  Table [dbo].[PACKAGEADDSERV]    Script Date: 11/15/2014 20:42:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PACKAGEADDSERV](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDJOB] [int] NOT NULL,
	[IDADDSERV] [int] NOT NULL,
	[COST] [int] NOT NULL,
 CONSTRAINT [PK_PACKAGEADDSERV] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


